Player.create(first_name: "Thomas", last_name: "Muller", goals: 4, assists: 1, matches:3, team_id:Team.find_by_name("Germany").id)
Player.create(first_name: "Robin", last_name: "van Persie", goals: 3, assists: 0, matches:2, team_id:Team.find_by_name("Netherlands").id)
Player.create(first_name: "Arjen", last_name: "Robben", goals: 3, assists: 1, matches:3, team_id:Team.find_by_name("Netherlands").id)
Player.create(first_name: "Luis", last_name: "Suarez", goals: 2, assists: 0, matches:2, team_id: Team.find_by_name("Uruguay").id)
Player.create(first_name: "Karim", last_name: "Benzema", goals: 3, assists: 2, matches:3, team_id: Team.find_by_name("France").id)
Player.create(first_name: "James", last_name: "Rodriguez", goals: 3, assists: 2, matches:3, team_id: Team.find_by_name("Colombia").id)
Player.create(first_name: "Tim", last_name: "Cahill", goals: 2, assists: 0, matches:2, team_id: Team.find_by_name("Australia").id)
Player.create(first_name: "", last_name: "Neymar", goals: 4, assists: 0, matches:3, team_id: Team.find_by_name("Brazil").id)
Player.create(first_name: "", last_name: "Gervinho", goals: 2, assists: 1, matches:3, team_id: Team.find_by_name("Cote D'Ivoire").id)
Player.create(first_name: "Mario", last_name: "Mandzukic", goals: 2, assists: 0, matches:2, team_id: Team.find_by_name("Croatia").id)
Player.create(first_name: "Enner", last_name: "Valencia", goals: 3, assists: 0, matches:3, team_id: Team.find_by_name("Ecuador").id)
Player.create(first_name: "Memphis", last_name: "Depay", goals: 2, assists: 1, matches:2, team_id: Team.find_by_name("Netherlands").id)
Player.create(first_name: "Ivan", last_name: "Perisic", goals: 2, assists: 1, matches:3, team_id: Team.find_by_name("Croatia").id)
Player.create(first_name: "Jackson", last_name: "Martinez", goals: 2, assists: 0, matches:2, team_id: Team.find_by_name("Colombia").id)
Player.create(first_name: "Wilfried", last_name: "Bony", goals: 2, assists: 0, matches:3, team_id: Team.find_by_name("Cote D'Ivoire").id)
Player.create(first_name: "Clint", last_name: "Dempsey", goals: 2, assists: 0, matches:3, team_id: Team.find_by_name("USA").id)
Player.create(first_name: "Luis", last_name: "Suarez", goals: 2, assists: 0, matches:2, team_id: Team.find_by_name("Uruguay").id)
Player.create(first_name: "Lionel", last_name: "Messi", goals: 4, assists: 0, matches:3, team_id: Team.find_by_name("Argentina").id)
Player.create(first_name: "Andre", last_name: "Ayew", goals: 2, assists: 0, matches:3, team_id: Team.find_by_name("Ghana").id)
Player.create(first_name: "Xherdan", last_name: "Shaqiri", goals: 3, assists: 0, matches:3, team_id: Team.find_by_name("Switzerland").id)
Player.create(first_name: "Islam", last_name: "Slimani", goals: 2, assists: 1, matches:3, team_id: Team.find_by_name("Algeria").id)
Player.create(first_name: "Asamoah", last_name: "Gyan", goals: 2, assists: 1, matches:3, team_id: Team.find_by_name("Ghana").id)
Player.create(first_name: "Ahmed", last_name: "Musa", goals: 2, assists: 0, matches:3, team_id: Team.find_by_name("Nigeria").id)
Player.create(first_name: "", last_name: "Oscar", goals: 1, assists: 2, matches:3, team_id: Team.find_by_name("Brazil").id)
Player.create(first_name: "Olivier", last_name: "Giroud", goals: 1, assists: 1, matches:3, team_id: Team.find_by_name("France").id)
