Player.create(first_name: "Thomas", last_name: "Muller", goals: 3, assists: 0, matches:1, team_id:2)
Player.create(first_name: "Robin", last_name: "van Persie", goals: 3, assists: 0, matches:2, team_id:3)
Player.create(first_name: "Arjen", last_name: "Robben", goals: 3, assists: 0, matches:2, team_id:3)
Player.create(first_name: "Luis", last_name: "Suarez", goals: 2, assists: 0, matches:1, team_id: 4)
Player.create(first_name: "Karim", last_name: "Benzema", goals: 2, assists: 0, matches:1, team_id: 5)
Player.create(first_name: "James", last_name: "Rodriguez", goals: 2, assists: 0, matches:2, team_id: 6)
Player.create(first_name: "Tim", last_name: "Cahill", goals: 2, assists: 0, matches:2, team_id: 1)
Player.create(first_name: "", last_name: "Neymar", goals: 2, assists: 0, matches:2, team_id: 2)
Player.create(first_name: "", last_name: "Gervinho", goals: 2, assists: 0, matches:2, team_id: 8)
Player.create(first_name: "Mario", last_name: "Mandzukic", goals: 2, assists: 0, matches:1, team_id: 4)